name: kopit
description: "A powerful, privacy-focused clipboard manager for Android."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  drift: ^2.24.2
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: ^1.9.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  equatable: ^2.0.7
  go_router: ^14.7.2
  receive_sharing_intent: ^1.8.1
  clipboard_watcher: ^0.3.0
  google_mobile_ads: ^7.0.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  fpdart: ^1.2.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.14
  drift_dev: ^2.24.2
  injectable_generator: ^2.6.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.production
